### ISSUE TITLE
How to get the text in training?

### ISSUE THREAD

**Issue by liuzhengzhe** [cassiePython/CLIPNeRF#1]
Thanks for the great work. I have a question, since it is a feed-forward framework, I think you may need the text in training. How to get it? I think there are no texts in both of the two datasets. Thanks!

**Comment by liuzhengzhe** [comment]
I have another question: if a target color is give, (but we do not know it means a color manipulation or a shape manipulation),  when optimize the CLIP loss (equ.6), I think the shape may also change because equ.6 does not provide any prior to keep shape  unchanged, so my question is how to keep shape untouched? 
Similarly, if a target shape is give (still, we do not know we need to manipulate the shape or color), how to only change shape and keep color unchanged? (because when optimizing equ.6, color may also change )

Thanks very much!

**Comment by cassiePython** [comment]
> Thanks for the great work. I have a question, since it is a feed-forward framework, I think you may need the text in training. How to get it? I think there are no texts in both of the two datasets. Thanks!

There are no texts in both datasets. You have to define these texts by yourself.

**Comment by cassiePython** [comment]
> I have another question: if a target color is give, (but we do not know it means a color manipulation or a shape manipulation), when optimize the CLIP loss (equ.6), I think the shape may also change because equ.6 does not provide any prior to keep shape unchanged, so my question is how to keep shape untouched? Similarly, if a target shape is give (still, we do not know we need to manipulate the shape or color), how to only change shape and keep color unchanged? (because when optimizing equ.6, color may also change )
> 
> Thanks very much!

The shape mapper and the color mapper are trained respectively. When you want to edit both the shape and color. You can first edit the shape via the shape mapper and then edit the color via the color mapper.

**Comment by liuzhengzhe** [comment]
Thanks for your reply! 

I think network training needs text. Do you annotate the datasets to add a correponding text for each data? If yes, how many texts do you annotate?

**Comment by liuzhengzhe** [comment]
I have another question. When we edit shape (with color fixed),  since the color may keep unchanged, and if shape changes drastically,  will it may cause shape-color misalignment?

**Comment by cassiePython** [comment]
@liuzhengzhe 

Hi,

1. No need to annotate text for each data. You just need to collect a small set of text prompts related to the dataset.
2. It will not cause misalignment, such as editing an SUV to a Jeep car. 

Best,
Can Wang

**Comment by liuzhengzhe** [comment]
Thanks very much!
