### ISSUE TITLE
Very slow training

### ISSUE THREAD

**Issue by LiquidAmmonia** [cassiePython/CLIPNeRF#10]
Hi, I have encountered a very slow training, it took me about 10 seconds to finish an iteration. The clip process costs the most of the time. My training script is directly copied from your README.md without any changes, and I checked the CLIP model, input image and text are all on cuda. Is this speed normal? Is there any way to speed up this process?

**Comment by cassiePython** [comment]
What is your GPU platform？

**Comment by LiquidAmmonia** [comment]
A Nvidia Titan X with cuda

**Comment by cassiePython** [comment]
Another researcher also encounters the same question on a TitanX, but obtains good results after training on a 3090ti. As the code is not fully tested on Titan X, you are advised to use a GPU with higher performance.
