### ISSUE TITLE
Wrong project site link

### ISSUE THREAD

**Issue by deepkyu** [cassiePython/CLIPNeRF#2]
Hello. First of all, congrats for accepting in CVPR 2022 😄 

Just minor issue...
For project page link in README.md, it links to your other project (https://cassiepython.github.io/cddfm3d/index).

Again, thank you for your inspirational research 👍🏻

**Comment by cassiePython** [comment]
@deepkyu Thanks for pointing out this issue!

**Comment by deepkyu** [comment]
https://cassiepython.github.io/clipnerf/
