### ISSUE TITLE
RuntimeError:CUDA out of memory.

### ISSUE THREAD

**Issue by zimingzhong** [cassiePython/CLIPNeRF#7]
I follow the default setting of ClipNerf on one RTX TiTian X with cuda out of memory.

I run successfully standard nerf on TiTian X with [nerf-pytorch](https://github.com/yenchenlin/nerf-pytorch), which is similar to ColorNerf. 

Then I change mse loss to gray mse loss and add Clip loss on [nerf-pytorch](https://github.com/yenchenlin/nerf-pytorch) in the way described in ClipNerf, which also can successfully run on one Titian X.

Is there anything wrong?

Thank you for your time.

**Comment by fangzhao521** [comment]
I also encountered the same problem. Have you solved it?Thank you very much!

**Comment by zimingzhong** [comment]
> I also encountered the same problem. Have you solved it?Thank you very much!

I also try to get the ClipNerf performance. Could I have your contact information?
My wechat account is Python_zzm.

**Comment by zimingzhong** [comment]
> 
change another GPU with bigger memory. Or reduce the sample_scale

**Comment by zimingzhong** [comment]
> I also encountered the same problem. Have you solved it?Thank you very much!

change another GPU with bigger memory. Or reduce the sample_scale
